TEXT_ORIENTATION_TOP = 0
TEXT_ORIENTATION_LEFT = 1
TEXT_ORIENTATION_RIGHT = 2
TEXT_ORIENTATION_BOTTOM = 3
TEXT_ORIENTATION_MIDDLE = 4

MODE_NORMAL = 0
MODE_ZOOM = 2
MODE_SELECT_FILE = 3

WIDGET_TYPE_LABEL = 0
WIDGET_TYPE_ICON = 1
